name: Validate

on:
  pull_request: {}
  push:
    branches: [main]
    paths:
      - 'scripts/**'
      - 'tests/**'
      - '.github/workflows/validate.yml'

jobs:
  ci:
    uses: AzureLocal/platform/.github/workflows/reusable-ps-module-ci.yml@main
    with:
      module-manifest: ./scripts/tools/qa/PSScriptAnalyzerSettings.psd1
      run-psscriptanalyzer: true
      psscriptanalyzer-path: 'scripts'
      run-pester: false
      validate-maproom: false
